/**
 * Audit Event Type Constants
 * Defines all trackable actions in the system for audit logging
 */

module.exports = {
  // Authentication Events
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_ATTEMPT_LOCKED: 'LOGIN_ATTEMPT_LOCKED',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  REGISTER_FAILED: 'REGISTER_FAILED',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  TOKEN_REVOKE: 'TOKEN_REVOKE',

  // User Management Events
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  PATCH_USER: 'PATCH_USER',
  DELETE_USER: 'DELETE_USER',
  GET_USER: 'GET_USER',
  LIST_USERS: 'LIST_USERS',

  // Satellite Events (Future)
  CREATE_SATELLITE: 'CREATE_SATELLITE',
  UPDATE_SATELLITE: 'UPDATE_SATELLITE',
  DELETE_SATELLITE: 'DELETE_SATELLITE',
  GET_SATELLITE: 'GET_SATELLITE',
  LIST_SATELLITES: 'LIST_SATELLITES',

  // Scenario Events (Future)
  CREATE_SCENARIO: 'CREATE_SCENARIO',
  UPDATE_SCENARIO: 'UPDATE_SCENARIO',
  DELETE_SCENARIO: 'DELETE_SCENARIO',
  EXECUTE_SCENARIO: 'EXECUTE_SCENARIO',

  // Command Events (Future)
  EXECUTE_COMMAND: 'EXECUTE_COMMAND',
  COMMAND_FAILED: 'COMMAND_FAILED',

  // AI Events (Future)
  AI_GENERATE: 'AI_GENERATE',
  AI_QUERY: 'AI_QUERY',

  // System Events
  API_ERROR: 'API_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
};
