// Help Center Data Types - Mirrors Firestore document structure
// Collection: helpCategories, helpArticles, helpFaqs

// Simulated Firestore Data
// In production, these would be fetched from:
// - firestore.collection('helpCategories')
// - firestore.collection('helpArticles')
// - firestore.collection('helpFaqs')

export const helpCategoriesData = [
  {
    id: "cat_001",
    title: "Getting Started",
    description: "New to GroundCTRL? Start here.",
    slug: "getting-started",
    icon: "Rocket",
    color: "text-primary",
    bgColor: "bg-primary/10",
    order: 1,
    articleCount: 5,
    isPublished: true,
  },
  {
    id: "cat_002",
    title: "Missions & Objectives",
    description: "Learn about mission types and objectives.",
    slug: "missions",
    icon: "Trophy",
    color: "text-status-warning",
    bgColor: "bg-status-warning/10",
    order: 2,
    articleCount: 5,
    isPublished: true,
  },
  {
    id: "cat_003",
    title: "Satellite Operations",
    description: "Master satellite control and subsystems.",
    slug: "satellite-operations",
    icon: "Satellite",
    color: "text-cyan",
    bgColor: "bg-cyan/10",
    order: 3,
    articleCount: 5,
    isPublished: true,
  },
  {
    id: "cat_004",
    title: "Communications",
    description: "Ground station links and data handling.",
    slug: "communications",
    icon: "Radio",
    color: "text-status-nominal",
    bgColor: "bg-status-nominal/10",
    order: 4,
    articleCount: 5,
    isPublished: true,
  },
  {
    id: "cat_005",
    title: "Nova AI Assistant",
    description: "Get the most out of your AI guide.",
    slug: "nova-assistant",
    icon: "Bot",
    color: "text-primary",
    bgColor: "bg-primary/10",
    order: 5,
    articleCount: 5,
    isPublished: true,
  },
  {
    id: "cat_006",
    title: "Account & Settings",
    description: "Manage your profile and preferences.",
    slug: "account",
    icon: "Settings",
    color: "text-muted-foreground",
    bgColor: "bg-muted",
    order: 6,
    articleCount: 5,
    isPublished: true,
  },
]

export const helpArticlesData = [
  // Getting Started
  {
    id: "art_001",
    title: "Welcome to GroundCTRL",
    slug: "welcome",
    categoryId: "cat_001",
    content: "Welcome to GroundCTRL, your gateway to learning satellite operations...",
    excerpt: "An introduction to the GroundCTRL satellite operations training simulator.",
    order: 1,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    viewCount: 1250,
    helpfulCount: 89,
    tags: ["beginner", "introduction", "overview"],
  },
  {
    id: "art_002",
    title: "Creating Your Account",
    slug: "create-account",
    categoryId: "cat_001",
    content: "Learn how to create and set up your GroundCTRL account...",
    excerpt: "Step-by-step guide to account creation and initial setup.",
    order: 2,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    viewCount: 980,
    helpfulCount: 67,
    tags: ["account", "setup", "registration"],
  },
  {
    id: "art_003",
    title: "Understanding the Dashboard",
    slug: "dashboard-overview",
    categoryId: "cat_001",
    content: "The dashboard is your mission control center...",
    excerpt: "Navigate and understand all dashboard components.",
    order: 3,
    isPublished: true,
    createdAt: "2024-01-16T00:00:00Z",
    updatedAt: "2024-01-16T00:00:00Z",
    viewCount: 845,
    helpfulCount: 52,
    tags: ["dashboard", "navigation", "interface"],
  },
  {
    id: "art_004",
    title: "Your First Mission",
    slug: "first-mission",
    categoryId: "cat_001",
    content: "Ready to launch your first mission? Here's what you need to know...",
    excerpt: "A walkthrough of completing your first satellite mission.",
    order: 4,
    isPublished: true,
    createdAt: "2024-01-17T00:00:00Z",
    updatedAt: "2024-01-17T00:00:00Z",
    viewCount: 1100,
    helpfulCount: 78,
    tags: ["mission", "tutorial", "beginner"],
  },
  {
    id: "art_005",
    title: "Navigating the Simulator",
    slug: "simulator-navigation",
    categoryId: "cat_001",
    content: "The simulator interface h key areas...",
    excerpt: "Learn to navigate the satellite operations simulator interface.",
    order: 5,
    isPublished: true,
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
    viewCount: 920,
    helpfulCount: 61,
    tags: ["simulator", "interface", "controls"],
  },
  // Missions & Objectives
  {
    id: "art_006",
    title: "Mission Types Explained",
    slug: "mission-types",
    categoryId: "cat_002",
    content: "GroundCTRL offers several mission types...",
    excerpt: "Understanding the different types of training missions available.",
    order: 1,
    isPublished: true,
    createdAt: "2024-01-19T00:00:00Z",
    updatedAt: "2024-01-19T00:00:00Z",
    viewCount: 756,
    helpfulCount: 45,
    tags: ["missions", "types", "training"],
  },
  {
    id: "art_007",
    title: "Understanding Objectives",
    slug: "objectives",
    categoryId: "cat_002",
    content: "Each mission h objectives to complete...",
    excerpt: "How mission objectives work and strategies for completion.",
    order: 2,
    isPublished: true,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
    viewCount: 680,
    helpfulCount: 38,
    tags: ["objectives", "goals", "completion"],
  },
  {
    id: "art_008",
    title: "Earning Mission Points (MP)",
    slug: "mission-points",
    categoryId: "cat_002",
    content: "Mission Points (MP) are earned by completing missions...",
    excerpt: "How to earn and use Mission Points in GroundCTRL.",
    order: 3,
    isPublished: true,
    createdAt: "2024-01-21T00:00:00Z",
    updatedAt: "2024-01-21T00:00:00Z",
    viewCount: 890,
    helpfulCount: 56,
    tags: ["points", "rewards", "progression"],
  },
  {
    id: "art_009",
    title: "Mission Difficulty Levels",
    slug: "difficulty-levels",
    categoryId: "cat_002",
    content: "Missions are rated from 1 to 5 stars in difficulty...",
    excerpt: "Understanding mission difficulty ratings and prerequisites.",
    order: 4,
    isPublished: true,
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-01-22T00:00:00Z",
    viewCount: 620,
    helpfulCount: 34,
    tags: ["difficulty", "levels", "stars"],
  },
  {
    id: "art_010",
    title: "Completing Your First Orbit",
    slug: "first-orbit",
    categoryId: "cat_002",
    content: "The First Orbit mission teaches fundamental concepts...",
    excerpt: "Walkthrough of the introductory orbital mechanics mission.",
    order: 5,
    isPublished: true,
    createdAt: "2024-01-23T00:00:00Z",
    updatedAt: "2024-01-23T00:00:00Z",
    viewCount: 780,
    helpfulCount: 49,
    tags: ["orbit", "tutorial", "mechanics"],
  },
  // Satellite Operations
  {
    id: "art_011",
    title: "Satellite Subsystems Overview",
    slug: "subsystems-overview",
    categoryId: "cat_003",
    content: "A satellite consists of several interdependent subsystems...",
    excerpt: "Introduction to the major satellite subsystems you'll manage.",
    order: 1,
    isPublished: true,
    createdAt: "2024-01-24T00:00:00Z",
    updatedAt: "2024-01-24T00:00:00Z",
    viewCount: 1050,
    helpfulCount: 72,
    tags: ["subsystems", "satellite", "overview"],
  },
  {
    id: "art_012",
    title: "Power Management",
    slug: "power-management",
    categoryId: "cat_003",
    content: "Solar arrays and batteries provide electrical power...",
    excerpt: "Managing satellite power generation and consumption.",
    order: 2,
    isPublished: true,
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
    viewCount: 820,
    helpfulCount: 58,
    tags: ["power", "solar", "battery"],
  },
  {
    id: "art_013",
    title: "Thermal Control",
    slug: "thermal-control",
    categoryId: "cat_003",
    content: "Space presents extreme thermal challenges...",
    excerpt: "Understanding and managing satellite thermal conditions.",
    order: 3,
    isPublished: true,
    createdAt: "2024-01-26T00:00:00Z",
    updatedAt: "2024-01-26T00:00:00Z",
    viewCount: 690,
    helpfulCount: 41,
    tags: ["thermal", "temperature", "cooling"],
  },
  {
    id: "art_014",
    title: "Attitude Control & Orientation",
    slug: "attitude-control",
    categoryId: "cat_003",
    content: "Attitude control determines the satellite's orientation...",
    excerpt: "How to control and monitor satellite orientation.",
    order: 4,
    isPublished: true,
    createdAt: "2024-01-27T00:00:00Z",
    updatedAt: "2024-01-27T00:00:00Z",
    viewCount: 910,
    helpfulCount: 63,
    tags: ["attitude", "orientation", "control"],
  },
  {
    id: "art_015",
    title: "Orbital Mechanics Basics",
    slug: "orbital-mechanics",
    categoryId: "cat_003",
    content: "Understanding orbital mechanics is essential for satellite operations...",
    excerpt: "Fundamental concepts of orbital mechanics for operators.",
    order: 5,
    isPublished: true,
    createdAt: "2024-01-28T00:00:00Z",
    updatedAt: "2024-01-28T00:00:00Z",
    viewCount: 1180,
    helpfulCount: 85,
    tags: ["orbital", "mechanics", "physics"],
  },
  // Communications
  {
    id: "art_016",
    title: "Ground Station Contacts",
    slug: "ground-contacts",
    categoryId: "cat_004",
    content: "Ground stations provide the link between operators and satellites...",
    excerpt: "Understanding ground station networks and contact scheduling.",
    order: 1,
    isPublished: true,
    createdAt: "2024-01-29T00:00:00Z",
    updatedAt: "2024-01-29T00:00:00Z",
    viewCount: 720,
    helpfulCount: 44,
    tags: ["ground station", "contacts", "scheduling"],
  },
  {
    id: "art_017",
    title: "Establishing Communication Links",
    slug: "comm-links",
    categoryId: "cat_004",
    content: "Communication links require proper configuration...",
    excerpt: "How to establish and maintain satellite communication links.",
    order: 2,
    isPublished: true,
    createdAt: "2024-01-30T00:00:00Z",
    updatedAt: "2024-01-30T00:00:00Z",
    viewCount: 680,
    helpfulCount: 39,
    tags: ["communication", "links", "connection"],
  },
  {
    id: "art_018",
    title: "Data Downlink Procedures",
    slug: "data-downlink",
    categoryId: "cat_004",
    content: "Downloading data from the satellite requires specific procedures...",
    excerpt: "Step-by-step data downlink and retrieval processes.",
    order: 3,
    isPublished: true,
    createdAt: "2024-01-31T00:00:00Z",
    updatedAt: "2024-01-31T00:00:00Z",
    viewCount: 590,
    helpfulCount: 32,
    tags: ["downlink", "data", "transfer"],
  },
  {
    id: "art_019",
    title: "Signal Strength & Quality",
    slug: "signal-quality",
    categoryId: "cat_004",
    content: "Signal quality affects communication reliability...",
    excerpt: "Monitoring and optimizing communication signal quality.",
    order: 4,
    isPublished: true,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
    viewCount: 540,
    helpfulCount: 28,
    tags: ["signal", "quality", "strength"],
  },
  {
    id: "art_020",
    title: "Communication Windows",
    slug: "comm-windows",
    categoryId: "cat_004",
    content: "Communication windows are time periods when contact is possible...",
    excerpt: "Planning around satellite visibility and communication windows.",
    order: 5,
    isPublished: true,
    createdAt: "2024-02-02T00:00:00Z",
    updatedAt: "2024-02-02T00:00:00Z",
    viewCount: 620,
    helpfulCount: 35,
    tags: ["windows", "visibility", "timing"],
  },
  // Nova AI Assistant
  {
    id: "art_021",
    title: "Introduction to Nova",
    slug: "intro-nova",
    categoryId: "cat_005",
    content: "Nova is your Navigational Orbital Vector Assistant...",
    excerpt: "Meet Nova, your AI guide for satellite operations training.",
    order: 1,
    isPublished: true,
    createdAt: "2024-02-03T00:00:00Z",
    updatedAt: "2024-02-03T00:00:00Z",
    viewCount: 880,
    helpfulCount: 62,
    tags: ["nova", "ai", "assistant"],
  },
  {
    id: "art_022",
    title: "Asking Effective Questions",
    slug: "asking-questions",
    categoryId: "cat_005",
    content: "Getting the most from Nova starts with asking good questions...",
    excerpt: "Tips for communicating effectively with the Nova AI.",
    order: 2,
    isPublished: true,
    createdAt: "2024-02-04T00:00:00Z",
    updatedAt: "2024-02-04T00:00:00Z",
    viewCount: 720,
    helpfulCount: 48,
    tags: ["questions", "communication", "tips"],
  },
  {
    id: "art_023",
    title: "Using Hints Strategically",
    slug: "using-hints",
    categoryId: "cat_005",
    content: "Hints are a valuable resource but limited per mission...",
    excerpt: "When and how to use Nova's hint system effectively.",
    order: 3,
    isPublished: true,
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-02-05T00:00:00Z",
    viewCount: 650,
    helpfulCount: 41,
    tags: ["hints", "strategy", "help"],
  },
  {
    id: "art_024",
    title: "Understanding Nova's Guidance",
    slug: "nova-guidance",
    categoryId: "cat_005",
    content: "Nova provides contextual guidance based on your current situation...",
    excerpt: "How Nova's guidance system works and adapts to you.",
    order: 4,
    isPublished: true,
    createdAt: "2024-02-06T00:00:00Z",
    updatedAt: "2024-02-06T00:00:00Z",
    viewCount: 580,
    helpfulCount: 36,
    tags: ["guidance", "contextual", "adaptive"],
  },
  {
    id: "art_025",
    title: "Nova Commands Reference",
    slug: "nova-commands",
    categoryId: "cat_005",
    content: "Nova responds to several specific commands and queries...",
    excerpt: "Complete reference of Nova commands and capabilities.",
    order: 5,
    isPublished: true,
    createdAt: "2024-02-07T00:00:00Z",
    updatedAt: "2024-02-07T00:00:00Z",
    viewCount: 490,
    helpfulCount: 29,
    tags: ["commands", "reference", "capabilities"],
  },
  // Account & Settings
  {
    id: "art_026",
    title: "Account Settings",
    slug: "account-settings",
    categoryId: "cat_006",
    content: "Manage your account settings including email and password...",
    excerpt: "How to access and modify your account settings.",
    order: 1,
    isPublished: true,
    createdAt: "2024-02-08T00:00:00Z",
    updatedAt: "2024-02-08T00:00:00Z",
    viewCount: 420,
    helpfulCount: 24,
    tags: ["account", "settings", "security"],
  },
  {
    id: "art_027",
    title: "Profile Customization",
    slug: "profile",
    categoryId: "cat_006",
    content: "Personalize your profile with display name and avatar...",
    excerpt: "Customize your GroundCTRL operator profile.",
    order: 2,
    isPublished: true,
    createdAt: "2024-02-09T00:00:00Z",
    updatedAt: "2024-02-09T00:00:00Z",
    viewCount: 380,
    helpfulCount: 21,
    tags: ["profile", "customization", "avatar"],
  },
  {
    id: "art_029",
    title: "Progress & Statistics",
    slug: "progress-stats",
    categoryId: "cat_006",
    content: "Track your progress through missions and achievements...",
    excerpt: "Understanding your progress tracking and statistics.",
    order: 4,
    isPublished: true,
    createdAt: "2024-02-11T00:00:00Z",
    updatedAt: "2024-02-11T00:00:00Z",
    viewCount: 450,
    helpfulCount: 27,
    tags: ["progress", "statistics", "tracking"],
  },
  {
    id: "art_030",
    title: "Data Export",
    slug: "data-export",
    categoryId: "cat_006",
    content: "Export your training data and progress reports...",
    excerpt: "How to export your GroundCTRL data and achievements.",
    order: 5,
    isPublished: true,
    createdAt: "2024-02-12T00:00:00Z",
    updatedAt: "2024-02-12T00:00:00Z",
    viewCount: 280,
    helpfulCount: 15,
    tags: ["export", "data", "reports"],
  },
]

export const helpFaqsData = [
  {
    id: "faq_001",
    question: "What is GroundCTRL?",
    answer:
      "GroundCTRL is a browser-based satellite operations training simulator designed for space enthusiasts, students, and aspiring operators. It provides an interactive learning experience through guided missions, real-time AI assistance, and realistic telemetry simulations.",
    order: 1,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "faq_002",
    question: "Is GroundCTRL connected to real satellites?",
    answer:
      "No. GroundCTRL is a purely educational simulation platform. All satellites, telemetry data, and operations are simulated for training purposes only. No real spacecraft or ground systems are affected by your actions in the simulator.",
    order: 2,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "faq_003",
    question: "What are Mission Points (MP)?",
    answer:
      "Mission Points (MP) are rewards earned by completing missions and objectives. They track your progress and unlock advanced missions  demonstrate proficiency in satellite operations concepts.",
    order: 3,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "faq_004",
    question: "How does the Nova AI assistant work?",
    answer:
      "Nova is your Navigational Orbital Vector Assistant - an AI guide that provides contextual help, answers questions about satellite operations, offers hints when you're stuck, and explains mission objectives in detail.",
    order: 4,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "faq_005",
    question: "Can I use GroundCTRL for educational purposes?",
    answer:
      "Absolutely GroundCTRL is designed for education. We offer special programs for schools, universities, and aerospace training organizations. Contact us about enterprise and educational licensing.",
    order: 5,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "faq_006",
    question: "What browser do I need?",
    answer:
      "GroundCTRL works best on modern desktop browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version for optimal performance. Mobile support is limited at this time.",
    order: 6,
    categoryId: null,
    isPublished: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
]

export const popularArticlesData = [
  {
    id: "pop_001",
    articleId: "art_004",
    title: "Quick Start Guide",
    categoryName: "Getting Started",
    icon: "Play",
    order: 1,
  },
  {
    id: "pop_002",
    articleId: "art_015",
    title: "Orbital Mechanics Basics",
    categoryName: "Satellite Operations",
    icon: "Satellite",
    order: 2,
  },
  {
    id: "pop_003",
    articleId: "art_011",
    title: "Understanding Telemetry Data",
    categoryName: "Satellite Operations",
    icon: "Gauge",
    order: 3,
  },
  {
    id: "pop_004",
    articleId: "art_021",
    title: "Using Nova Effectively",
    categoryName: "Nova AI Assistant",
    icon: "Zap",
    order: 4,
  },
]

// Helper functions to simulate Firestore queries
export function getArticlesByCategory(categoryId) {
  return helpArticlesData
    .filter((article) => article.categoryId === categoryId && article.isPublished)
    .sort((a, b) => a.order - b.order)
}

export function getArticleBySlug(slug) {
  return helpArticlesData.find((article) => article.slug === slug && article.isPublished)
}

export function getCategoryBySlug(slug) {
  return helpCategoriesData.find((category) => category.slug === slug && category.isPublished)
}

export function getCategoryById(id) {
  return helpCategoriesData.find((category) => category.id === id && category.isPublished)
}

export function getRelatedArticles(article, limit = 3) {
  return helpArticlesData
    .filter((a) => a.isPublished && a.id !== article.id && a.categoryId === article.categoryId)
    .sort((a, b) => b.viewCount - a.viewCount)
    .slice(0, limit)
}

export function searchArticles(query) {
  const lowerQuery = query.toLowerCase()
  return helpArticlesData.filter(
    (article) =>
      article.isPublished &&
      (article.title.toLowerCase().includes(lowerQuery) ||
        article.excerpt.toLowerCase().includes(lowerQuery) ||
        article.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)))
  )
}

export function getPublishedCategories() {
  return helpCategoriesData
    .filter((category) => category.isPublished)
    .sort((a, b) => a.order - b.order)
}

export function getPublishedFaqs() {
  return helpFaqsData
    .filter((faq) => faq.isPublished)
    .sort((a, b) => a.order - b.order)
}

export function getPopularArticles() {
  return popularArticlesData.sort((a, b) => a.order - b.order)
}
