// Simulated Firebase Firestore data structure for Missions
// This mirrors the document structure that would be stored in Firestore collections

// Simulated Firestore data
export const missionCategories = [
  {
    id: "fundamentals",
    name: "Fundamentals",
    description: "Core concepts and basic operations for satellite management",
    icon: "BookOpen",
    order: 1,
    color: "primary",
    missionCount: 2,
  },
  {
    id: "orbital-mechanics",
    name: "Orbital Mechanics",
    description: "Master the physics of orbital motion and maneuvers",
    icon: "Compass",
    order: 2,
    color: "cyan",
    missionCount: 3,
  },
  {
    id: "communications",
    name: "Communications",
    description: "Establish and maintain satellite-ground station links",
    icon: "Radio",
    order: 3,
    color: "teal",
    missionCount: 2,
  },
  {
    id: "power-systems",
    name: "Power Systems",
    description: "Manage energy generation, storage, and distribution",
    icon: "Zap",
    order: 4,
    color: "gold",
    missionCount: 2,
  },
  {
    id: "advanced",
    name: "Advanced",
    description: "Complex scenarios requiring mastery of all systems",
    icon: "Shield",
    order: 5,
    color: "orange",
    missionCount: 3,
  },
]

export const missions = [
  {
    id: "mission-001",
    name: "System Initialization",
    description: "Learn the basic procedures for powering up and initializing a satellite's onboard systems.",
    longDescription: "In this introductory mission, you'll learn the essential procedures for bringing a satellite online from a cold start. You'll work through the power-up sequence, initialize critical subsystems, and verify all systems are functioning correctly. This foundational knowledge is crucial for all subsequent missions.",
    category: "Fundamentals",
    difficulty: 1,
    difficultyLabel: "Beginner",
    estimatedDuration: 15,
    icon: "Rocket",
    status: "completed",
    progress: 100,
    completedAt: "2026-01-15T10:30:00Z",
    startedAt: "2026-01-15T10:00:00Z",
    steps: [
      {
        id: "step-001-1",
        title: "Power System Activation",
        description: "Engage the primary power bus and verify battery levels",
        order: 1,
        estimatedDuration: 4,
        objectives: [
          {
            id: "obj-001-1-1",
            title: "Activate Primary Power Bus",
            description: "Toggle the main power switch to engage the primary electrical bus",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Look for the power controls in the Command Console", "The power bus is usually the first system to activate"],
          },
          {
            id: "obj-001-1-2",
            title: "Verify Battery Status",
            description: "Check that battery charge is above 50% before proceeding",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Battery status is shown in the telemetry panel", "Green indicator means nominal levels"],
          },
        ],
      },
      {
        id: "step-001-2",
        title: "Communications Check",
        description: "Establish initial ground station link",
        order: 2,
        estimatedDuration: 5,
        objectives: [
          {
            id: "obj-001-2-1",
            title: "Enable Communication Subsystem",
            description: "Activate the satellite's communication array",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Communication controls are in the right panel"],
          },
          {
            id: "obj-001-2-2",
            title: "Verify Ground Station Lock",
            description: "Confirm two-way communication with Mission Control",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Look for the 'CONNECTED' status indicator"],
          },
        ],
      },
      {
        id: "step-001-3",
        title: "Subsystem Verification",
        description: "Run diagnostics on all major subsystems",
        order: 3,
        estimatedDuration: 6,
        objectives: [
          {
            id: "obj-001-3-1",
            title: "Understanding Telemetry",
            description: "Learn to read the telemetry display panels",
            type: "learn",
            order: 1,
            requiredForCompletion: true,
            hints: ["Nova can explain each telemetry reading"],
          },
        ],
      },
    ],
    totalObjectives: 5,
    completedObjectives: 5,
    prerequisites: [],
    rewards: {
      mp: 100,
      badges: ["first-boot"],
      unlocks: ["mission-002"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.2.0",
    isActive: true,
    isFeatured: false,
    tags: ["beginner", "essential", "power", "initialization"],
  },
  {
    id: "mission-002",
    name: "Orientation & First Contact",
    description: "Establish your first communication link with the ground station and verify telemetry data.",
    longDescription: "Building on your initialization skills, this mission focuses on establishing reliable communication with Earth. You'll learn about signal propagation, antenna pointing, and telemetry verification. Successfully completing this mission unlocks more advanced communication scenarios.",
    category: "Communications",
    difficulty: 1,
    difficultyLabel: "Beginner",
    estimatedDuration: 20,
    icon: "Radio",
    status: "completed",
    progress: 100,
    completedAt: "2026-01-16T14:45:00Z",
    startedAt: "2026-01-16T14:00:00Z",
    steps: [
      {
        id: "step-002-1",
        title: "Antenna Configuration",
        description: "Configure the high-gain antenna for Earth pointing",
        order: 1,
        estimatedDuration: 6,
        objectives: [
          {
            id: "obj-002-1-1",
            title: "Select Communication Mode",
            description: "Switch to high-gain antenna mode",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Check the Communications section in Command Console"],
          },
          {
            id: "obj-002-1-2",
            title: "Orient Antenna to Earth",
            description: "Use attitude control to point the antenna toward Earth",
            type: "action",
            order: 2,
            requiredForCompletion: true,
            hints: ["The orbital view shows Earth's position relative to the satellite"],
          },
        ],
      },
      {
        id: "step-002-2",
        title: "Signal Acquisition",
        description: "Lock onto the ground station signal",
        order: 2,
        estimatedDuration: 7,
        objectives: [
          {
            id: "obj-002-2-1",
            title: "Acquire Ground Station",
            description: "Establish link with Mission Control",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Use the 'Establish Link' command"],
          },
          {
            id: "obj-002-2-2",
            title: "Verify Signal Strength",
            description: "Confirm signal strength is above -90 dBm",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Signal strength is shown in the telemetry panel"],
          },
        ],
      },
      {
        id: "step-002-3",
        title: "Telemetry Verification",
        description: "Verify all telemetry is being received correctly",
        order: 3,
        estimatedDuration: 7,
        objectives: [
          {
            id: "obj-002-3-1",
            title: "Complete Telemetry Quiz",
            description: "Answer questions about telemetry readings",
            type: "quiz",
            order: 1,
            requiredForCompletion: true,
            hints: ["Review the telemetry panel before answering"],
          },
        ],
      },
    ],
    totalObjectives: 5,
    completedObjectives: 5,
    prerequisites: [{ missionId: "mission-001", missionName: "System Initialization" }],
    rewards: {
      mp: 150,
      badges: ["communicator"],
      unlocks: ["mission-003", "mission-008"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.1.0",
    isActive: true,
    isFeatured: false,
    tags: ["beginner", "communications", "telemetry"],
  },
  {
    id: "mission-003",
    name: "Orbital Mechanics 101",
    description: "Understand the fundamentals of orbital mechanics including perigee, apogee, and orbital periods.",
    longDescription: "Dive into the physics that govern satellite motion. This mission teaches you about Keplerian orbital elements, the relationship between altitude and orbital period, and how to interpret orbital parameters. You'll work with real (simulated) orbital data and learn to predict satellite positions.",
    category: "Orbital Mechanics",
    difficulty: 2,
    difficultyLabel: "Easy",
    estimatedDuration: 25,
    icon: "Compass",
    status: "completed",
    progress: 100,
    completedAt: "2026-01-17T09:20:00Z",
    startedAt: "2026-01-17T08:30:00Z",
    steps: [
      {
        id: "step-003-1",
        title: "Understanding Orbits",
        description: "Learn the basic terminology of orbital mechanics",
        order: 1,
        estimatedDuration: 8,
        objectives: [
          {
            id: "obj-003-1-1",
            title: "Perigee and Apogee",
            description: "Identify perigee and apogee on the orbital display",
            type: "learn",
            order: 1,
            requiredForCompletion: true,
            hints: ["Perigee is the closest point, apogee is the farthest"],
          },
          {
            id: "obj-003-1-2",
            title: "Orbital Elements Quiz",
            description: "Test your knowledge of orbital terminology",
            type: "quiz",
            order: 2,
            requiredForCompletion: true,
            hints: ["Review the terms: semi-major axis, eccentricity, inclination"],
          },
        ],
      },
      {
        id: "step-003-2",
        title: "Reading Orbital Data",
        description: "Interpret the orbital parameters display",
        order: 2,
        estimatedDuration: 8,
        objectives: [
          {
            id: "obj-003-2-1",
            title: "Identify Current Altitude",
            description: "Read the satellite's current altitude from telemetry",
            type: "verify",
            order: 1,
            requiredForCompletion: true,
            hints: ["Altitude is displayed in the orbit parameters panel"],
          },
          {
            id: "obj-003-2-2",
            title: "Calculate Orbital Period",
            description: "Determine the orbital period from the given data",
            type: "quiz",
            order: 2,
            requiredForCompletion: true,
            hints: ["Higher orbits have longer periods"],
          },
        ],
      },
      {
        id: "step-003-3",
        title: "Orbit Visualization",
        description: "Use the orbital view to track satellite position",
        order: 3,
        estimatedDuration: 9,
        objectives: [
          {
            id: "obj-003-3-1",
            title: "Track One Full Orbit",
            description: "Observe the satellite completing one full orbit",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Use time acceleration to speed up the simulation"],
          },
          {
            id: "obj-003-3-2",
            title: "Predict Ground Pass",
            description: "Identify when the satellite will next pass over the ground station",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Check the 'Next Contact' timer"],
          },
        ],
      },
    ],
    totalObjectives: 6,
    completedObjectives: 6,
    prerequisites: [{ missionId: "mission-002", missionName: "Orientation & First Contact" }],
    rewards: {
      mp: 200,
      badges: ["orbital-scholar"],
      unlocks: ["mission-004"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.3.0",
    isActive: true,
    isFeatured: true,
    tags: ["orbital-mechanics", "physics", "visualization"],
  },
  {
    id: "mission-004",
    name: "Stable Orbit & First Ground Pass",
    description: "Execute orbital adjustments to achieve a stable orbit and complete your first ground pass data transfer.",
    longDescription: "Put your orbital mechanics knowledge into practice. This mission challenges you to analyze your current orbit, plan necessary adjustments, and execute a burn to raise your perigee. You'll then coordinate with the ground station to complete a data transfer during your pass.",
    category: "Orbital Mechanics",
    difficulty: 2,
    difficultyLabel: "Easy",
    estimatedDuration: 30,
    icon: "Target",
    status: "in-progress",
    progress: 40,
    startedAt: "2026-01-18T10:00:00Z",
    steps: [
      {
        id: "step-004-1",
        title: "Orbit Analysis",
        description: "Analyze current orbital parameters",
        order: 1,
        estimatedDuration: 7,
        objectives: [
          {
            id: "obj-004-1-1",
            title: "Initialize Satellite Systems",
            description: "Ensure all systems are nominal before maneuver",
            type: "verify",
            order: 1,
            requiredForCompletion: true,
            hints: ["Check all status indicators are green"],
          },
          {
            id: "obj-004-1-2",
            title: "Record Current Orbit Parameters",
            description: "Note the current perigee, apogee, and inclination",
            type: "action",
            order: 2,
            requiredForCompletion: true,
            hints: ["These values are in the Orbit Parameters panel"],
          },
        ],
      },
      {
        id: "step-004-2",
        title: "Ground Link Establishment",
        description: "Establish communication with Mission Control",
        order: 2,
        estimatedDuration: 6,
        objectives: [
          {
            id: "obj-004-2-1",
            title: "Establish Ground Link",
            description: "Connect to the ground station",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Use the Communications panel"],
          },
        ],
      },
      {
        id: "step-004-3",
        title: "Analyze Orbit Parameters",
        description: "Determine required orbit adjustments",
        order: 3,
        estimatedDuration: 8,
        objectives: [
          {
            id: "obj-004-3-1",
            title: "Analyze Current Orbit",
            description: "Determine if perigee needs to be raised",
            type: "learn",
            order: 1,
            requiredForCompletion: true,
            hints: ["A stable LEO orbit typically h above 400km"],
          },
          {
            id: "obj-004-3-2",
            title: "Plan Perigee Raising Maneuver",
            description: "Calculate the required delta-v for perigee raise",
            type: "action",
            order: 2,
            requiredForCompletion: true,
            hints: ["The Command Console h maneuver planning tools"],
          },
        ],
      },
      {
        id: "step-004-4",
        title: "Execute Burn Sequence",
        description: "Perform the orbital maneuver",
        order: 4,
        estimatedDuration: 9,
        objectives: [
          {
            id: "obj-004-4-1",
            title: "Execute Burn",
            description: "Fire thrusters to raise perigee to target altitude",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Monitor fuel consumption during the burn"],
          },
          {
            id: "obj-004-4-2",
            title: "Verify New Orbit",
            description: "Confirm perigee is now above 400km",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Check the updated orbital parameters"],
          },
        ],
      },
    ],
    totalObjectives: 8,
    completedObjectives: 3,
    prerequisites: [{ missionId: "mission-003", missionName: "Orbital Mechanics 101" }],
    rewards: {
      mp: 250,
      badges: ["first-maneuver"],
      unlocks: ["mission-005", "mission-009"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.2.0",
    isActive: true,
    isFeatured: true,
    tags: ["orbital-mechanics", "maneuvers", "hands-on"],
  },
  {
    id: "mission-005",
    name: "Power Management",
    description: "Learn to balance solar panel orientation, battery levels, and power distribution across subsystems.",
    longDescription: "Satellites depend on careful power management to survive. In this mission, you'll learn how to optimize solar panel orientation, manage battery charge cycles, and prioritize power distribution when resources are limited. You'll face scenarios where you must make critical decisions about which systems to power.",
    category: "Power Systems",
    difficulty: 2,
    difficultyLabel: "Easy",
    estimatedDuration: 25,
    icon: "Zap",
    status: "available",
    progress: 0,
    steps: [
      {
        id: "step-005-1",
        title: "Solar Power Basics",
        description: "Understand how solar panels generate power",
        order: 1,
        estimatedDuration: 8,
        objectives: [
          {
            id: "obj-005-1-1",
            title: "Solar Panel Orientation",
            description: "Learn how panel angle affects power generation",
            type: "learn",
            order: 1,
            requiredForCompletion: true,
            hints: ["Panels generate most power when perpendicular to sunlight"],
          },
          {
            id: "obj-005-1-2",
            title: "Optimize Panel Angle",
            description: "Adjust solar panels for maximum power generation",
            type: "action",
            order: 2,
            requiredForCompletion: true,
            hints: ["Watch the power generation meter  adjust"],
          },
        ],
      },
      {
        id: "step-005-2",
        title: "Battery Management",
        description: "Manage battery charging and discharging",
        order: 2,
        estimatedDuration: 8,
        objectives: [
          {
            id: "obj-005-2-1",
            title: "Monitor Eclipse Entry",
            description: "Prepare for power loss during Earth's shadow",
            type: "action",
            order: 1,
            requiredForCompletion: true,
            hints: ["Check when the next eclipse period begins"],
          },
          {
            id: "obj-005-2-2",
            title: "Survive Eclipse Period",
            description: "Maintain operations through an eclipse using battery power",
            type: "verify",
            order: 2,
            requiredForCompletion: true,
            hints: ["Reduce non-essential systems to conserve power"],
          },
        ],
      },
      {
        id: "step-005-3",
        title: "Power Distribution",
        description: "Allocate power across subsystems",
        order: 3,
        estimatedDuration: 9,
        objectives: [
          {
            id: "obj-005-3-1",
            title: "Power Priority Quiz",
            description: "Demonstrate knowledge of power priorities",
            type: "quiz",
            order: 1,
            requiredForCompletion: true,
            hints: ["Life support and communications are typically highest priority"],
          },
          {
            id: "obj-005-3-2",
            title: "Handle Power Emergency",
            description: "Respond to a simulated power shortage",
            type: "action",
            order: 2,
            requiredForCompletion: true,
            hints: ["Shed non-critical loads first"],
          },
        ],
      },
    ],
    totalObjectives: 6,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-004", missionName: "Stable Orbit & First Ground Pass" }],
    rewards: {
      mp: 200,
      badges: ["power-master"],
      unlocks: ["mission-006"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["power", "solar", "battery", "resource-management"],
  },
  {
    id: "mission-006",
    name: "Thermal Control Systems",
    description: "Manage satellite temperature through heater control and orientation adjustments.",
    longDescription: "Space presents extreme thermal challenges - from scorching sunlight to the cold void of shadow. This mission teaches you to manage satellite thermal systems, including heaters, radiators, and thermal coatings. You'll learn to keep all components within their operational temperature ranges.",
    category: "Power Systems",
    difficulty: 3,
    difficultyLabel: "Intermediate",
    estimatedDuration: 30,
    icon: "Sun",
    status: "locked",
    progress: 0,
    steps: [
      {
        id: "step-006-1",
        title: "Thermal Basics",
        description: "Understanding heat transfer in space",
        order: 1,
        estimatedDuration: 10,
        objectives: [
          {
            id: "obj-006-1-1",
            title: "Heat Transfer Mechanisms",
            description: "Learn about radiation, conduction, and convection in space",
            type: "learn",
            order: 1,
            requiredForCompletion: true,
            hints: ["In space, radiation is the primary heat transfer mechanism"],
          },
        ],
      },
    ],
    totalObjectives: 7,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-005", missionName: "Power Management" }],
    rewards: {
      mp: 300,
      badges: ["thermal-expert"],
      unlocks: ["mission-007"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["thermal", "advanced-power", "environmental"],
  },
  {
    id: "mission-007",
    name: "Attitude Control",
    description: "Master satellite orientation using reaction wheels and magnetic torquers.",
    longDescription: "Precise attitude control is essential for antenna pointing, solar panel orientation, and scientific observations. This mission covers the principles and practice of satellite attitude determination and control using reaction wheels, magnetic torquers, and thrusters.",
    category: "Advanced",
    difficulty: 3,
    difficultyLabel: "Intermediate",
    estimatedDuration: 35,
    icon: "RotateCw",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 8,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-006", missionName: "Thermal Control Systems" }],
    rewards: {
      mp: 350,
      badges: ["attitude-ace"],
      unlocks: ["mission-010"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["attitude", "control-systems", "precision"],
  },
  {
    id: "mission-008",
    name: "Deep Space Communication",
    description: "Establish and maintain communication links over extreme distances.",
    longDescription: "Push the limits of satellite communication in this advanced mission. You'll work with signal propagation delays, manage link budgets, and handle the challenges of communicating with spacecraft far from Earth. This mission simulates communication scenarios similar to interplanetary missions.",
    category: "Communications",
    difficulty: 4,
    difficultyLabel: "Advanced",
    estimatedDuration: 40,
    icon: "Wifi",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 10,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-002", missionName: "Orientation & First Contact" }],
    rewards: {
      mp: 400,
      badges: ["deep-space-communicator"],
      unlocks: [],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["communications", "deep-space", "advanced"],
  },
  {
    id: "mission-009",
    name: "Orbital Maneuvers",
    description: "Execute complex orbital transfers including Hohmann transfers and plane changes.",
    longDescription: "Take your orbital mechanics skills to the next level with advanced maneuvers. You'll learn to calculate and execute Hohmann transfer orbits, bi-elliptic transfers, and inclination changes. This mission requires careful planning and precise execution.",
    category: "Orbital Mechanics",
    difficulty: 4,
    difficultyLabel: "Advanced",
    estimatedDuration: 45,
    icon: "Globe",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 10,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-004", missionName: "Stable Orbit & First Ground Pass" }],
    rewards: {
      mp: 450,
      badges: ["master-navigator"],
      unlocks: ["mission-011"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["orbital-mechanics", "advanced-maneuvers", "hohmann"],
  },
  {
    id: "mission-010",
    name: "Emergency Procedures",
    description: "Handle critical system failures and execute safe mode protocols.",
    longDescription: "When things go wrong in space, quick thinking and proper procedures can save a mission. This mission simulates various emergency scenarios including power failures, communication loss, and thermal emergencies. You'll learn to diagnose problems and implement recovery procedures.",
    category: "Advanced",
    difficulty: 4,
    difficultyLabel: "Advanced",
    estimatedDuration: 40,
    icon: "Shield",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 8,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-007", missionName: "Attitude Control" }],
    rewards: {
      mp: 400,
      badges: ["crisis-manager"],
      unlocks: ["mission-011"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: false,
    tags: ["emergency", "procedures", "troubleshooting"],
  },
  {
    id: "mission-011",
    name: "Satellite Constellation",
    description: "Manage multiple satellites in a coordinated constellation network.",
    longDescription: "Scale up your operations to manage not just one satellite, but an entire constellation. This expert-level mission challenges you to coordinate multiple spacecraft, manage inter-satellite links, and maintain constellation geometry. Experience the complexity of systems like GPS or Starlink.",
    category: "Advanced",
    difficulty: 5,
    difficultyLabel: "Expert",
    estimatedDuration: 50,
    icon: "Satellite",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 12,
    completedObjectives: 0,
    prerequisites: [
      { missionId: "mission-009", missionName: "Orbital Maneuvers" },
      { missionId: "mission-010", missionName: "Emergency Procedures" },
    ],
    rewards: {
      mp: 500,
      badges: ["constellation-commander"],
      unlocks: ["mission-012"],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: true,
    tags: ["constellation", "multi-satellite", "expert"],
  },
  {
    id: "mission-012",
    name: "Autonomous Operations",
    description: "Program autonomous mission sequences and handle communication blackouts.",
    longDescription: "The ultimate test of your satellite operations skills. In this capstone mission, you'll program autonomous sequences that allow the satellite to operate independently during communication blackouts. You'll design decision trees, implement fault protection, and validate your autonomous system.",
    category: "Advanced",
    difficulty: 5,
    difficultyLabel: "Expert",
    estimatedDuration: 60,
    icon: "Gauge",
    status: "locked",
    progress: 0,
    steps: [],
    totalObjectives: 15,
    completedObjectives: 0,
    prerequisites: [{ missionId: "mission-011", missionName: "Satellite Constellation" }],
    rewards: {
      mp: 600,
      badges: ["autonomous-operator", "mission-master"],
      unlocks: [],
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
    version: "1.0.0",
    isActive: true,
    isFeatured: true,
    tags: ["autonomous", "programming", "expert", "capstone"],
  },
]

// Helper functions to simulate Firestore queries

export function getMissions() {
  return missions
}

export function getMissionById(id) {
  return missions.find(m => m.id === id)
}

export function getMissionsByCategory(category) {
  return missions.filter(m => m.category === category)
}

export function getMissionsByStatus(status) {
  return missions.filter(m => m.status === status)
}

export function getAvailableMissions() {
  return missions.filter(m => m.status === "available" || m.status === "in-progress")
}

export function getCompletedMissions() {
  return missions.filter(m => m.status === "completed")
}

export function getFeaturedMissions() {
  return missions.filter(m => m.isFeatured)
}

export function searchMissions(query) {
  const lowerQuery = query.toLowerCase()
  return missions.filter(m => 
    m.name.toLowerCase().includes(lowerQuery) ||
    m.description.toLowerCase().includes(lowerQuery) ||
    m.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  )
}

export function getMissionStats() {
  const completed = missions.filter(m => m.status === "completed").length
  const inProgress = missions.filter(m => m.status === "in-progress").length
  const available = missions.filter(m => m.status === "available").length
  const locked = missions.filter(m => m.status === "locked").length
  const totalMp = missions
    .filter(m => m.status === "completed")
    .reduce((sum, m) => sum + m.rewards.mp, 0)
  
  return {
    total: missions.length,
    completed,
    inProgress,
    available,
    locked,
    totalMp,
    progressPercent: Math.round((completed / missions.length) * 100),
  }
}

export function getCategories() {
  return missionCategories
}

export function getCategoryStats(categoryId) {
  const categoryMissions = missions.filter(
    m => m.category.toLowerCase().replace(/\s+/g, '-') === categoryId
  )
  return {
    total: categoryMissions.length,
    completed: categoryMissions.filter(m => m.status === "completed").length,
    inProgress: categoryMissions.filter(m => m.status === "in-progress").length,
  }
}
